import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const d = (value: string) => new Date(value);

async function main() {
  await prisma.$transaction([
    prisma.timeIssue.deleteMany(),
    prisma.timeEntry.deleteMany(),
    prisma.performanceMetric.deleteMany(),
    prisma.projectFinancialSnapshot.deleteMany(),
    prisma.customerRule.deleteMany(),
    prisma.operationalCase.deleteMany(),
    prisma.documentStatus.deleteMany(),
    prisma.restriction.deleteMany(),
    prisma.assignment.deleteMany(),
    prisma.employee.deleteMany(),
    prisma.vehicleGroup.deleteMany(),
    prisma.accommodation.deleteMany(),
    prisma.position.deleteMany(),
    prisma.shift.deleteMany(),
    prisma.coordinator.deleteMany(),
    prisma.partnerCompany.deleteMany(),
    prisma.site.deleteMany(),
    prisma.customer.deleteMany(),
    prisma.appUser.deleteMany(),
  ]);

  await prisma.appUser.createMany({
    data: [
      {
        id: "user-management",
        name: "Management",
        email: "management@workforce-ops.local",
        role: "management",
      },
      {
        id: "user-backoffice",
        name: "Backoffice",
        email: "backoffice@workforce-ops.local",
        role: "backoffice",
      },
      {
        id: "user-foreman",
        name: "Vorarbeiter",
        email: "foreman@workforce-ops.local",
        role: "foreman",
      },
    ],
  });

  await prisma.customer.createMany({
    data: [
      {
        id: "customer-jager",
        name: "Jager",
        notes: "Logistikkunde mit eigenem Zeit- und Leistungssystem.",
      },
      {
        id: "customer-fiege",
        name: "FIEGE",
        notes: "Logistikkunde mit mehreren Standorten und eigenen Schicht- und Korrekturregeln.",
      },
    ],
  });

  await prisma.site.createMany({
    data: [
      {
        id: "site-jager-erfurt",
        customerId: "customer-jager",
        name: "Jager Erfurt DC",
        address: "Logistikstandort Erfurt",
      },
      {
        id: "site-jager-halle",
        customerId: "customer-jager",
        name: "Jager Halle Outbound",
        address: "Outbound-Bereich Halle",
      },
      {
        id: "site-fiege-leipzig",
        customerId: "customer-fiege",
        name: "FIEGE Leipzig",
        address: "Fulfillment-Standort Leipzig",
      },
    ],
  });

  await prisma.partnerCompany.createMany({
    data: [
      {
        id: "partner-baltic-staffing",
        name: "Baltic Staffing",
        country: "LT",
        notes: "Hauptpartner fuer Fruehschicht-Mitarbeiter.",
      },
      {
        id: "partner-euroshift",
        name: "EuroShift Services",
        country: "PL",
        notes: "Flexibler Partner fuer Ersatzstellungen und Wochenendabdeckung.",
      },
      {
        id: "partner-nova-workforce",
        name: "Nova Workforce",
        country: "RO",
        notes: "Neuerer Partner mit mehreren offenen Startkontrollpunkten.",
      },
    ],
  });

  await prisma.coordinator.createMany({
    data: [
      {
        id: "coord-ana",
        partnerCompanyId: "partner-baltic-staffing",
        name: "Ana Petrauskas",
        phone: "+370 600 100 01",
        email: "ana@baltic-staffing.local",
        role: "Recruiting-Koordination",
      },
      {
        id: "coord-marek",
        partnerCompanyId: "partner-baltic-staffing",
        name: "Marek Nowak",
        phone: "+48 500 100 02",
        email: "marek@baltic-staffing.local",
        role: "Ersatz-Koordination",
      },
      {
        id: "coord-ewa",
        partnerCompanyId: "partner-euroshift",
        name: "Ewa Zielinska",
        phone: "+48 500 100 03",
        email: "ewa@euroshift.local",
        role: "Operations-Koordination",
      },
      {
        id: "coord-victor",
        partnerCompanyId: "partner-nova-workforce",
        name: "Victor Ionescu",
        phone: "+40 700 100 04",
        email: "victor@nova-workforce.local",
        role: "Partnerbetreuung",
      },
      {
        id: "coord-irina",
        partnerCompanyId: "partner-nova-workforce",
        name: "Irina Popescu",
        phone: "+40 700 100 05",
        email: "irina@nova-workforce.local",
        role: "Dokumenten-Nachverfolgung",
      },
    ],
  });

  await prisma.accommodation.createMany({
    data: [
      {
        id: "accommodation-erfurt-north",
        name: "Erfurt North House",
        address: "Erfurt North",
        capacity: 18,
      },
      {
        id: "accommodation-leipzig-east",
        name: "Leipzig East Apartments",
        address: "Leipzig East",
        capacity: 14,
      },
    ],
  });

  await prisma.vehicleGroup.createMany({
    data: [
      {
        id: "vehicle-group-bus-a",
        name: "Bus A - Erfurt Early",
        type: "bus",
        capacity: 8,
      },
      {
        id: "vehicle-group-car-b",
        name: "Private Car B - Leipzig",
        type: "private_car",
        capacity: 4,
      },
    ],
  });

  await prisma.shift.createMany({
    data: [
      {
        id: "shift-jager-early",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        name: "Fruehschicht",
        startsAt: "06:00",
        endsAt: "14:30",
      },
      {
        id: "shift-jager-late",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
        name: "Spaetschicht",
        startsAt: "14:00",
        endsAt: "22:30",
      },
      {
        id: "shift-fiege-day",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        name: "Tagschicht",
        startsAt: "07:00",
        endsAt: "15:30",
      },
    ],
  });

  await prisma.position.createMany({
    data: [
      {
        id: "position-picking",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        name: "Kommissionierung",
        description: "Pick-out und Kommissionierung im Kundensystem.",
      },
      {
        id: "position-packing",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        name: "Verpackung",
        description: "Verpackung und Vorbereitung fuer den Warenausgang.",
      },
      {
        id: "position-goods-in",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
        name: "Wareneingang",
        description: "Annahme, Sortierung und interne Bereitstellung.",
      },
      {
        id: "position-sortation",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        name: "Sortierung",
        description: "Sortierung von Paketen und Behaeltern.",
      },
      {
        id: "position-loading",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        name: "Verladung",
        description: "Unterstuetzung an der Laderampe.",
      },
      {
        id: "position-quality-check",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
        name: "Quality Check",
        description: "Operational quality checks and rework.",
      },
    ],
  });

  await prisma.employee.createMany({
    data: [
      {
        id: "emp-001",
        firstName: "Tomas",
        lastName: "Kazlauskas",
        displayName: "Tomas Kazlauskas",
        status: "active",
        onboardingStatus: "active",
        externalCardNumber: "JG-1001",
        externalSystemId: "JAGER-TK-01",
        phone: "+370 610 200 01",
        language: "lt",
        firstWorkday: d("2026-05-04T06:00:00.000Z"),
        partnerCompanyId: "partner-baltic-staffing",
        coordinatorId: "coord-ana",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-erfurt",
        currentShiftId: "shift-jager-early",
        currentPositionId: "position-picking",
        accommodationId: "accommodation-erfurt-north",
        vehicleGroupId: "vehicle-group-bus-a",
      },
      {
        id: "emp-002",
        firstName: "Karolina",
        lastName: "Nowicka",
        displayName: "Karolina Nowicka",
        status: "active",
        onboardingStatus: "active",
        externalCardNumber: "JG-1002",
        externalSystemId: "JAGER-KN-02",
        phone: "+48 510 200 02",
        language: "pl",
        firstWorkday: d("2026-05-06T06:00:00.000Z"),
        partnerCompanyId: "partner-euroshift",
        coordinatorId: "coord-ewa",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-erfurt",
        currentShiftId: "shift-jager-early",
        currentPositionId: "position-packing",
        accommodationId: "accommodation-erfurt-north",
        vehicleGroupId: "vehicle-group-bus-a",
      },
      {
        id: "emp-003",
        firstName: "Marius",
        lastName: "Petraitis",
        displayName: "Marius Petraitis",
        status: "planned",
        onboardingStatus: "first_workday_planned",
        externalCardNumber: "JG-1003",
        phone: "+370 610 200 03",
        language: "lt",
        firstWorkday: d("2026-06-06T06:00:00.000Z"),
        partnerCompanyId: "partner-baltic-staffing",
        coordinatorId: "coord-marek",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-halle",
        currentShiftId: "shift-jager-late",
        currentPositionId: "position-goods-in",
      },
      {
        id: "emp-004",
        firstName: "Andrei",
        lastName: "Popa",
        displayName: "Andrei Popa",
        status: "announced",
        onboardingStatus: "document_received",
        phone: "+40 710 200 04",
        language: "ro",
        partnerCompanyId: "partner-nova-workforce",
        coordinatorId: "coord-irina",
        currentCustomerId: "customer-fiege",
        currentSiteId: "site-fiege-leipzig",
      },
      {
        id: "emp-005",
        firstName: "Elena",
        lastName: "Ionescu",
        displayName: "Elena Ionescu",
        status: "created",
        onboardingStatus: "customer_system_created",
        externalCardNumber: "FG-2101",
        externalSystemId: "FIEGE-EI-01",
        phone: "+40 710 200 05",
        language: "ro",
        partnerCompanyId: "partner-nova-workforce",
        coordinatorId: "coord-victor",
        currentCustomerId: "customer-fiege",
        currentSiteId: "site-fiege-leipzig",
        currentShiftId: "shift-fiege-day",
        currentPositionId: "position-sortation",
        accommodationId: "accommodation-leipzig-east",
        vehicleGroupId: "vehicle-group-car-b",
      },
      {
        id: "emp-006",
        firstName: "Piotr",
        lastName: "Kowalski",
        displayName: "Piotr Kowalski",
        status: "appeared",
        onboardingStatus: "first_pick_confirmed",
        externalCardNumber: "FG-2102",
        phone: "+48 510 200 06",
        language: "pl",
        firstWorkday: d("2026-06-03T07:00:00.000Z"),
        partnerCompanyId: "partner-euroshift",
        coordinatorId: "coord-ewa",
        currentCustomerId: "customer-fiege",
        currentSiteId: "site-fiege-leipzig",
        currentShiftId: "shift-fiege-day",
        currentPositionId: "position-loading",
        accommodationId: "accommodation-leipzig-east",
        vehicleGroupId: "vehicle-group-car-b",
      },
      {
        id: "emp-007",
        firstName: "Lukas",
        lastName: "Jankauskas",
        displayName: "Lukas Jankauskas",
        status: "no_show",
        onboardingStatus: "no_show",
        phone: "+370 610 200 07",
        language: "lt",
        partnerCompanyId: "partner-baltic-staffing",
        coordinatorId: "coord-marek",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-erfurt",
        currentShiftId: "shift-jager-early",
        currentPositionId: "position-picking",
        notes: "Nach Wochenendbestaetigung nicht zur geplanten Schicht erschienen.",
      },
      {
        id: "emp-008",
        firstName: "Monika",
        lastName: "Zielinska",
        displayName: "Monika Zielinska",
        status: "replaced",
        onboardingStatus: "replacement_requested",
        phone: "+48 510 200 08",
        language: "pl",
        partnerCompanyId: "partner-euroshift",
        coordinatorId: "coord-ewa",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-halle",
        currentShiftId: "shift-jager-late",
        currentPositionId: "position-quality-check",
      },
      {
        id: "emp-009",
        firstName: "Rasa",
        lastName: "Stankeviciute",
        displayName: "Rasa Stankeviciute",
        status: "sick",
        onboardingStatus: "active",
        externalCardNumber: "JG-1009",
        phone: "+370 610 200 09",
        language: "lt",
        partnerCompanyId: "partner-baltic-staffing",
        coordinatorId: "coord-ana",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-erfurt",
        currentShiftId: "shift-jager-early",
        currentPositionId: "position-packing",
      },
      {
        id: "emp-010",
        firstName: "Gabriel",
        lastName: "Marin",
        displayName: "Gabriel Marin",
        status: "vacation",
        onboardingStatus: "active",
        externalCardNumber: "FG-2110",
        phone: "+40 710 200 10",
        language: "ro",
        partnerCompanyId: "partner-nova-workforce",
        coordinatorId: "coord-victor",
        currentCustomerId: "customer-fiege",
        currentSiteId: "site-fiege-leipzig",
        currentShiftId: "shift-fiege-day",
        currentPositionId: "position-loading",
      },
      {
        id: "emp-011",
        firstName: "Oksana",
        lastName: "Melnyk",
        displayName: "Oksana Melnyk",
        status: "active",
        onboardingStatus: "active",
        externalCardNumber: "JG-1011",
        phone: "+48 510 200 11",
        language: "uk",
        partnerCompanyId: "partner-euroshift",
        coordinatorId: "coord-ewa",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-halle",
        currentShiftId: "shift-jager-late",
        currentPositionId: "position-goods-in",
      },
      {
        id: "emp-012",
        firstName: "Darius",
        lastName: "Banys",
        displayName: "Darius Banys",
        status: "planned",
        onboardingStatus: "foreman_informed",
        externalCardNumber: "JG-1012",
        phone: "+370 610 200 12",
        language: "lt",
        partnerCompanyId: "partner-baltic-staffing",
        coordinatorId: "coord-ana",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-erfurt",
        currentShiftId: "shift-jager-early",
        currentPositionId: "position-picking",
      },
      {
        id: "emp-013",
        firstName: "Alexandru",
        lastName: "Dobre",
        displayName: "Alexandru Dobre",
        status: "created",
        onboardingStatus: "card_assigned",
        externalCardNumber: "FG-2113",
        phone: "+40 710 200 13",
        language: "ro",
        partnerCompanyId: "partner-nova-workforce",
        coordinatorId: "coord-irina",
        currentCustomerId: "customer-fiege",
        currentSiteId: "site-fiege-leipzig",
      },
      {
        id: "emp-014",
        firstName: "Agnieszka",
        lastName: "Kaczmarek",
        displayName: "Agnieszka Kaczmarek",
        status: "announced",
        onboardingStatus: "announced",
        phone: "+48 510 200 14",
        language: "pl",
        partnerCompanyId: "partner-euroshift",
        coordinatorId: "coord-ewa",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-erfurt",
      },
      {
        id: "emp-015",
        firstName: "Mindaugas",
        lastName: "Sakalauskas",
        displayName: "Mindaugas Sakalauskas",
        status: "inactive",
        onboardingStatus: "active",
        externalCardNumber: "JG-1015",
        phone: "+370 610 200 15",
        language: "lt",
        partnerCompanyId: "partner-baltic-staffing",
        coordinatorId: "coord-marek",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-halle",
        notes: "Ehemaliger Mitarbeiter, nur noch fuer Historie sichtbar.",
      },
      {
        id: "emp-016",
        firstName: "Nicoleta",
        lastName: "Stan",
        displayName: "Nicoleta Stan",
        status: "active",
        onboardingStatus: "active",
        externalCardNumber: "FG-2116",
        phone: "+40 710 200 16",
        language: "ro",
        partnerCompanyId: "partner-nova-workforce",
        coordinatorId: "coord-victor",
        currentCustomerId: "customer-fiege",
        currentSiteId: "site-fiege-leipzig",
        currentShiftId: "shift-fiege-day",
        currentPositionId: "position-sortation",
      },
      {
        id: "emp-017",
        firstName: "Pawel",
        lastName: "Wisniewski",
        displayName: "Pawel Wisniewski",
        status: "active",
        onboardingStatus: "active",
        externalCardNumber: "JG-1017",
        phone: "+48 510 200 17",
        language: "pl",
        partnerCompanyId: "partner-euroshift",
        coordinatorId: "coord-ewa",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-halle",
        currentShiftId: "shift-jager-late",
        currentPositionId: "position-quality-check",
      },
      {
        id: "emp-018",
        firstName: "Justina",
        lastName: "Mikalauskaite",
        displayName: "Justina Mikalauskaite",
        status: "appeared",
        onboardingStatus: "first_pick_confirmed",
        externalCardNumber: "JG-1018",
        phone: "+370 610 200 18",
        language: "lt",
        partnerCompanyId: "partner-baltic-staffing",
        coordinatorId: "coord-ana",
        currentCustomerId: "customer-jager",
        currentSiteId: "site-jager-erfurt",
        currentShiftId: "shift-jager-early",
        currentPositionId: "position-packing",
      },
      {
        id: "emp-019",
        firstName: "Cristian",
        lastName: "Enache",
        displayName: "Cristian Enache",
        status: "planned",
        onboardingStatus: "first_workday_planned",
        externalCardNumber: "FG-2119",
        phone: "+40 710 200 19",
        language: "ro",
        partnerCompanyId: "partner-nova-workforce",
        coordinatorId: "coord-irina",
        currentCustomerId: "customer-fiege",
        currentSiteId: "site-fiege-leipzig",
        currentShiftId: "shift-fiege-day",
        currentPositionId: "position-loading",
      },
      {
        id: "emp-020",
        firstName: "Greta",
        lastName: "Vaitkute",
        displayName: "Greta Vaitkute",
        status: "created",
        onboardingStatus: "not_started",
        phone: "+370 610 200 20",
        language: "lt",
        partnerCompanyId: "partner-baltic-staffing",
        coordinatorId: "coord-marek",
        notes: "Vom Partner angekuendigt, aber noch keinem Kunden zugeordnet.",
      },
    ],
  });

  await prisma.vehicleGroup.update({
    where: { id: "vehicle-group-bus-a" },
    data: { driverEmployeeId: "emp-001" },
  });
  await prisma.vehicleGroup.update({
    where: { id: "vehicle-group-car-b" },
    data: { driverEmployeeId: "emp-006" },
  });

  await prisma.assignment.createMany({
    data: [
      {
        id: "assignment-001",
        date: d("2026-06-05T06:00:00.000Z"),
        employeeId: "emp-001",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        shiftId: "shift-jager-early",
        positionId: "position-picking",
        status: "appeared",
        plannedById: "user-management",
        confirmedById: "user-foreman",
      },
      {
        id: "assignment-002",
        date: d("2026-06-05T06:00:00.000Z"),
        employeeId: "emp-002",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        shiftId: "shift-jager-early",
        positionId: "position-packing",
        status: "confirmed",
        plannedById: "user-management",
        confirmedById: "user-foreman",
      },
      {
        id: "assignment-003",
        date: d("2026-06-05T14:00:00.000Z"),
        employeeId: "emp-011",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
        shiftId: "shift-jager-late",
        positionId: "position-goods-in",
        status: "planned",
        plannedById: "user-management",
      },
      {
        id: "assignment-004",
        date: d("2026-06-05T07:00:00.000Z"),
        employeeId: "emp-006",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        shiftId: "shift-fiege-day",
        positionId: "position-loading",
        status: "appeared",
        plannedById: "user-management",
        confirmedById: "user-foreman",
      },
      {
        id: "assignment-005",
        date: d("2026-06-05T07:00:00.000Z"),
        employeeId: "emp-016",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        shiftId: "shift-fiege-day",
        positionId: "position-sortation",
        status: "confirmed",
        plannedById: "user-management",
        confirmedById: "user-foreman",
      },
      {
        id: "assignment-006",
        date: d("2026-06-06T06:00:00.000Z"),
        employeeId: "emp-003",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
        shiftId: "shift-jager-late",
        positionId: "position-goods-in",
        status: "planned",
        plannedById: "user-management",
      },
      {
        id: "assignment-007",
        date: d("2026-06-06T06:00:00.000Z"),
        employeeId: "emp-007",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        shiftId: "shift-jager-early",
        positionId: "position-picking",
        status: "missed",
        plannedById: "user-management",
      },
      {
        id: "assignment-008",
        date: d("2026-06-06T14:00:00.000Z"),
        employeeId: "emp-017",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
        shiftId: "shift-jager-late",
        positionId: "position-quality-check",
        status: "confirmed",
        plannedById: "user-management",
        confirmedById: "user-foreman",
      },
      {
        id: "assignment-009",
        date: d("2026-06-07T07:00:00.000Z"),
        employeeId: "emp-019",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        shiftId: "shift-fiege-day",
        positionId: "position-loading",
        status: "planned",
        plannedById: "user-management",
      },
      {
        id: "assignment-010",
        date: d("2026-06-07T06:00:00.000Z"),
        employeeId: "emp-018",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        shiftId: "shift-jager-early",
        positionId: "position-packing",
        status: "confirmed",
        plannedById: "user-management",
        confirmedById: "user-foreman",
      },
    ],
  });

  await prisma.restriction.createMany({
    data: [
      {
        id: "restriction-001",
        employeeId: "emp-003",
        type: "only_second_shift",
        severity: "normal",
        reason: "Transport von der Unterkunft ist nur fuer die Spaetschicht verfuegbar.",
      },
      {
        id: "restriction-002",
        employeeId: "emp-005",
        type: "must_travel_with_group",
        severity: "high",
        reason: "Kein eigener Transport verfuegbar.",
      },
      {
        id: "restriction-003",
        employeeId: "emp-012",
        type: "fixed_position",
        severity: "normal",
        reason: "Kunde hat den Mitarbeiter nur fuer Kommissionierung eingearbeitet.",
      },
      {
        id: "restriction-004",
        employeeId: "emp-016",
        type: "customer_preference",
        severity: "low",
        reason: "Vorarbeiter bevorzugt den Mitarbeiter im Bereich Sortierung.",
      },
      {
        id: "restriction-005",
        employeeId: "emp-019",
        type: "language_support_needed",
        severity: "normal",
        reason: "Braucht in der ersten Woche eine rumaenischsprachige Ansprechperson.",
      },
    ],
  });

  await prisma.operationalCase.createMany({
    data: [
      {
        id: "case-001",
        type: "no_show",
        status: "open",
        priority: "high",
        title: "No-Show nach Wochenende",
        description: "Mitarbeiter ist trotz Bestaetigung nach dem Wochenende nicht zur geplanten Jager-Fruehschicht erschienen.",
        ownerId: "user-backoffice",
        employeeId: "emp-007",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        partnerCompanyId: "partner-baltic-staffing",
        dueDate: d("2026-06-06T12:00:00.000Z"),
        nextStep: "Partner muss Ersatz liefern und die Ersatzperson bestaetigen.",
      },
      {
        id: "case-002",
        type: "time_error",
        status: "in_progress",
        priority: "normal",
        title: "Fehlendes Pick-out im Kundensystem",
        description: "Im Jager-System fehlt der Abschluss der Schicht; die tatsaechliche Endzeit ist unklar.",
        ownerId: "user-backoffice",
        employeeId: "emp-001",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        dueDate: d("2026-06-09T12:00:00.000Z"),
        nextStep: "Vorarbeiter soll die tatsaechliche Endzeit bestaetigen.",
      },
      {
        id: "case-003",
        type: "missing_document",
        status: "waiting_for_partner",
        priority: "normal",
        title: "Mitarbeiter noch nicht aktiv: Dokumentenbestaetigung fehlt",
        description: "Der Partner hat den Mitarbeiter angekuendigt, aber die aktualisierte Dokumentenbestaetigung fehlt noch.",
        ownerId: "user-backoffice",
        employeeId: "emp-004",
        partnerCompanyId: "partner-nova-workforce",
        dueDate: d("2026-06-10T12:00:00.000Z"),
        nextStep: "Partnerkoordination soll den Dokumentenstatus bestaetigen.",
      },
      {
        id: "case-004",
        type: "fuel_receipt",
        status: "open",
        priority: "low",
        title: "Offener Tankbeleg muss zugeordnet werden",
        description: "Ein Tankbeleg fuer die Erfurter Fahrzeuggruppe ist offen und muss Fahrer und Route zugeordnet werden.",
        ownerId: "user-backoffice",
        vehicleGroupId: "vehicle-group-bus-a",
        amount: 86.4,
        currency: "EUR",
        dueDate: d("2026-06-12T12:00:00.000Z"),
        nextStep: "Tankbeleg mit Fahrer und Routennotiz abgleichen.",
      },
      {
        id: "case-005",
        type: "fine",
        status: "waiting_for_management",
        priority: "high",
        title: "Bussgeld/Fahrzeugthema: Verantwortung unklar",
        description: "Ein Parkbussgeld ist eingegangen; Zuordnung zu Fahrer, Partner oder interner Verantwortung ist noch offen.",
        ownerId: "user-management",
        vehicleGroupId: "vehicle-group-car-b",
        amount: 35,
        currency: "EUR",
        dueDate: d("2026-06-11T12:00:00.000Z"),
        nextStep: "Management entscheidet die Behandlung vor Ruecksprache mit dem Partner.",
      },
      {
        id: "case-006",
        type: "worker_complaint",
        status: "in_progress",
        priority: "normal",
        title: "Pause zu lang: Mitarbeiter wartet auf Korrektur",
        description: "Mitarbeiter meldet 30 Minuten Pause, das Kundensystem zeigt 60 Minuten.",
        ownerId: "user-backoffice",
        employeeId: "emp-006",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        dueDate: d("2026-06-09T12:00:00.000Z"),
        nextStep: "Kundenbuchung mit Vorarbeiter-Notiz vergleichen.",
      },
      {
        id: "case-007",
        type: "partner_claim",
        status: "waiting_for_partner",
        priority: "normal",
        title: "Partner muss Ersatz liefern: Kostenklaerung offen",
        description: "Partner fragt nach der Kostenklaerung fuer eine Ersatzstellung nach Ausfall.",
        ownerId: "user-management",
        partnerCompanyId: "partner-euroshift",
        amount: 120,
        currency: "EUR",
        dueDate: d("2026-06-13T12:00:00.000Z"),
        nextStep: "Vorgangshistorie und Einsatzdetails an den Partner senden.",
      },
      {
        id: "case-008",
        type: "customer_problem",
        status: "open",
        priority: "critical",
        title: "Kunde wartet auf Korrektur: FIEGE Montag bestaetigen",
        description: "FIEGE wartet auf Rueckmeldung zur geplanten Besetzung und zu neuen Mitarbeitern fuer Montag.",
        ownerId: "user-management",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        dueDate: d("2026-06-06T16:00:00.000Z"),
        nextStep: "Geplante Kopfzahl und neue Mitarbeiter fuer den ersten Einsatztag bestaetigen.",
      },
    ],
  });

  await prisma.customerRule.createMany({
    data: [
      {
        id: "rule-001",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        type: "break_rule",
        name: "Jager Erfurt automatische Pausenabziehung",
        description: "Das Kundensystem zieht nach einer Schwelle automatisch Pausenzeit ab.",
        configJson: { thresholdHours: 6, deductedBreakMinutes: 30 },
      },
      {
        id: "rule-002",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
        type: "correction_workflow",
        name: "Jager Halle Korrekturen ueber Vorarbeiter",
        description: "Korrekturen brauchen eine Vorarbeiter-Bestaetigung vor Kontakt mit dem Kunden.",
        configJson: { firstContact: "foreman", customerEscalationAfterDays: 2 },
      },
      {
        id: "rule-003",
        customerId: "customer-jager",
        type: "performance_data_rule",
        name: "Jager Leistungsabgleich ueber Mitarbeiter-ID",
        description: "Leistungssignale koennen ueber die externe Mitarbeiter-ID gelesen werden, wenn vorhanden.",
        configJson: { source: "customer_portal", matchingKey: "externalSystemId" },
      },
      {
        id: "rule-004",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        type: "first_day_rule",
        name: "FIEGE Bestaetigung am ersten Arbeitstag",
        description: "Neue Mitarbeiter brauchen eine Ankunftsbestaetigung und eine zugewiesene Ansprechperson.",
        configJson: { requiresForemanConfirmation: true, trainingLeadRequired: true },
      },
      {
        id: "rule-005",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        type: "billing_rule",
        name: "FIEGE nur gepruefte Stunden",
        description: "Die Abrechnungsvorbereitung nutzt gepruefte Stunden, nicht rohe Importwerte.",
        configJson: { billFromField: "validatedHours", allowManualCorrection: true },
      },
      {
        id: "rule-006",
        customerId: "customer-fiege",
        type: "contact_rule",
        name: "FIEGE Eskalationskontakte",
        description: "Operative Eskalationen laufen zuerst ueber den internen Vorarbeiter.",
        configJson: { firstContact: "internal_foreman", escalationWindowHours: 4 },
      },
    ],
  });

  await prisma.timeEntry.createMany({
    data: [
      {
        id: "time-entry-001",
        workDate: d("2026-06-05T00:00:00.000Z"),
        source: "jager_customer_system",
        startTime: d("2026-06-05T06:01:00.000Z"),
        endTime: d("2026-06-05T14:34:00.000Z"),
        breakMinutes: 30,
        rawHours: 8.55,
        validatedHours: 8.05,
        status: "final",
        employeeId: "emp-001",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        assignmentId: "assignment-001",
      },
      {
        id: "time-entry-002",
        workDate: d("2026-06-05T00:00:00.000Z"),
        source: "jager_customer_system",
        startTime: d("2026-06-05T06:03:00.000Z"),
        breakMinutes: 30,
        rawHours: 0,
        status: "suspicious",
        employeeId: "emp-002",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        assignmentId: "assignment-002",
        notes: "Fehlender Schichtabschluss im Kundenexport.",
      },
      {
        id: "time-entry-003",
        workDate: d("2026-06-05T00:00:00.000Z"),
        source: "fiege_customer_system",
        startTime: d("2026-06-05T07:02:00.000Z"),
        endTime: d("2026-06-05T15:36:00.000Z"),
        breakMinutes: 60,
        rawHours: 8.57,
        validatedHours: 7.57,
        status: "under_review",
        employeeId: "emp-006",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        assignmentId: "assignment-004",
      },
      {
        id: "time-entry-004",
        workDate: d("2026-06-05T00:00:00.000Z"),
        source: "fiege_customer_system",
        startTime: d("2026-06-05T07:00:00.000Z"),
        endTime: d("2026-06-05T15:25:00.000Z"),
        breakMinutes: 30,
        rawHours: 8.42,
        validatedHours: 7.92,
        status: "billable",
        employeeId: "emp-016",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        assignmentId: "assignment-005",
      },
      {
        id: "time-entry-005",
        workDate: d("2026-06-04T00:00:00.000Z"),
        source: "manual_timesheet",
        startTime: d("2026-06-04T14:05:00.000Z"),
        endTime: d("2026-06-04T22:41:00.000Z"),
        breakMinutes: 30,
        rawHours: 8.6,
        validatedHours: 8.1,
        status: "corrected",
        employeeId: "emp-011",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
      },
      {
        id: "time-entry-006",
        workDate: d("2026-06-04T00:00:00.000Z"),
        source: "jager_customer_system",
        startTime: d("2026-06-04T06:02:00.000Z"),
        endTime: d("2026-06-04T22:17:00.000Z"),
        breakMinutes: 30,
        rawHours: 16.25,
        status: "suspicious",
        employeeId: "emp-018",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        notes: "Vermutlich fehlende Pausenrueckmeldung oder doppelte Buchung.",
      },
    ],
  });

  await prisma.timeIssue.createMany({
    data: [
      {
        id: "time-issue-001",
        timeEntryId: "time-entry-002",
        employeeId: "emp-002",
        type: "missing_check_out",
        status: "assigned_to_foreman",
        assignedTo: "Vorarbeiter",
        notes: "Tatsaechliche Endzeit muss bestaetigt werden.",
      },
      {
        id: "time-issue-002",
        timeEntryId: "time-entry-003",
        employeeId: "emp-006",
        type: "worker_complaint",
        status: "sent_to_customer",
        assignedTo: "Backoffice",
        notes: "Mitarbeiter meldet 30 Minuten Pause, das Kundensystem zeigt 60 Minuten.",
      },
      {
        id: "time-issue-003",
        timeEntryId: "time-entry-006",
        employeeId: "emp-018",
        type: "unusually_long_shift",
        status: "open",
        assignedTo: "Backoffice",
        notes: "16-Stunden-Tag muss vor Abrechnung geprueft werden.",
      },
      {
        id: "time-issue-004",
        timeEntryId: "time-entry-005",
        employeeId: "emp-011",
        type: "manual_correction",
        status: "resolved",
        assignedTo: "Backoffice",
        resolution: "Vorarbeiter hat die manuelle Korrektur bestaetigt.",
      },
    ],
  });

  await prisma.performanceMetric.createMany({
    data: [
      {
        id: "metric-001",
        metricDate: d("2026-06-05T00:00:00.000Z"),
        metricType: "orders_per_hour",
        value: 42.5,
        unit: "orders/hour",
        source: "jager_customer_system",
        employeeId: "emp-001",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        shiftId: "shift-jager-early",
      },
      {
        id: "metric-002",
        metricDate: d("2026-06-05T00:00:00.000Z"),
        metricType: "units_processed",
        value: 610,
        unit: "units",
        source: "fiege_customer_system",
        employeeId: "emp-016",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        shiftId: "shift-fiege-day",
      },
      {
        id: "metric-003",
        metricDate: d("2026-06-04T00:00:00.000Z"),
        metricType: "error_count",
        value: 1,
        unit: "errors",
        source: "foreman_note",
        employeeId: "emp-017",
        customerId: "customer-jager",
        siteId: "site-jager-halle",
        shiftId: "shift-jager-late",
      },
      {
        id: "metric-004",
        metricDate: d("2026-06-05T00:00:00.000Z"),
        metricType: "training_needed",
        value: 1,
        unit: "flag",
        source: "foreman_note",
        employeeId: "emp-006",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        shiftId: "shift-fiege-day",
      },
    ],
  });

  await prisma.projectFinancialSnapshot.createMany({
    data: [
      {
        id: "snapshot-001",
        customerId: "customer-jager",
        siteId: "site-jager-erfurt",
        periodStart: d("2026-06-01T00:00:00.000Z"),
        periodEnd: d("2026-06-07T23:59:59.000Z"),
        expectedRevenue: 18400,
        directLaborCost: 11950,
        transportCost: 1120,
        accommodationCost: 2480,
        overheadCost: 1700,
        otherCost: 320,
        grossMargin: 830,
        status: "draft",
        notes: "Placeholder snapshot for later profitability views.",
      },
      {
        id: "snapshot-002",
        customerId: "customer-fiege",
        siteId: "site-fiege-leipzig",
        periodStart: d("2026-06-01T00:00:00.000Z"),
        periodEnd: d("2026-06-07T23:59:59.000Z"),
        expectedRevenue: 12600,
        directLaborCost: 7950,
        transportCost: 680,
        accommodationCost: 1420,
        overheadCost: 1250,
        otherCost: 180,
        grossMargin: 1120,
        status: "draft",
        notes: "Placeholder snapshot only; no profitability UI in MVP slice yet.",
      },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
